name: Set tag and release

on:
  workflow_run:
    workflows: ["PHP Test"]
    branches: [main]
    types: 
      - completed

jobs:
  build:
    if: ${{ !contains(github.event.head_commit.message, 'update package file versions') }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'

      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0
        with:
          useConfigFile: true
      
      - name: Update package file versions
        run: php -f updatePackageVersion.php ${{ steps.gitversion.outputs.semVer }}
      
      - name: Commit package file versions
        run: |
          git config --local user.email ""
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "build: update package file versions to ${{ steps.gitversion.outputs.semVer }}"
          git push
      
      - uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          tag: ${{ steps.gitversion.outputs.semVer }}